### ISSUE TITLE
Images in rtf format file extend over edge of page

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#32]
Some images go over the right margin in the RTF outputs.

**Comment by JohnAdders** [comment]
has been fixed by making images smaller but this loses quality.

**Comment by JohnAdders** [comment]
Would be good to understand what's going on in pandoc that can control the image size in rtf

**Comment by krzmip** [comment]
as suggested by https://pandoc.org/MANUAL.html#images width can be controlled by adding { width=...} to the image
in the most recent pull request I added a line that checks each image in the markdown file and if the result would exceed 7 inches (requires knowing the image size and dpi) scale down appropriately.

Alternative remediation considered but rejected as less preferable:
- explicit adjustment in the yml files (not pursued in order to keep yaml files as simple as possible)
- implicit adjustment at the end in the RTF (markdown adjustment seems cleaner option)
- no adjustment but a check (throw warning/error with suggestion to manually change the images)
